---
- name: set force install fact
  set_fact:
    force: "{{ force | default('false')  }}"

- name: check ramdisk mount point extsts
  stat:
    path: "{{ node.ramdisk_path }}"
  register: ramdisk_exists
  tags:
    - config.ramdisk

- name: create ramdisk mount point
  file:
    path: "{{ node.ramdisk_path }}"
    state: directory
    mode: '0755'
  tags:
    - config.ramdisk.directory
  when: force or not ramdisk_exists.stat.exists

- name: Write ramdisk entry in fstab
  mount: name={{ node.ramdisk_path }}
         src=tmpfs
         fstype=tmpfs
         opts=nodev,nosuid,noexec,nodiratime,size={{ node.ramdisk_size_gb }}G
         passno=0
         dump=0
         state=mounted
  tags:
    - config.ramdisk.fstab
  when: force or not ramdisk_exists.stat.exists
