---
- name: Set solana directory ownership
  file:
    path: "{{ node.solana_home }}"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0755
  when: node.lvm_enabled
  ignore_errors: True
  tags:
    - config.solana_user

- name: Create user solana
  user:
    name: "{{ node.solana_user }}"
    state: present
    create_home: yes
    shell: /bin/bash
    skeleton: /etc/skel
    groups: syslog
  tags:
    - config.solana_user

- name: Create secrets dir
  become: yes
  become_user: "{{ node.solana_user }}"
  file:
    path: "{{ validator.secrets_path }}"
    state: directory
    mode: '0700'
  tags:
    - config.solana_user

