---
all:
  children:
    local:
      children:
        testnet_validators:      
          hosts:
            localhost:
        mainnet_validators:
          hosts:
    remote:
      children:
        pb_tests:
          hosts:
            hetzner-test-validator:
              ansible_host: 65.21.149.247
        mainnet_validators:
          hosts:
            joogh_mainnet_hetzner:
              ramdisk_size_gb: 196
              ansible_host: 157.90.177.36
              keybase_username: 'joogh'
            joogh_mainnet_webtropia:
              ramdisk_size_gb: 512
              ansible_host: 89.163.220.199
        testnet_validators:
          hosts:
            jd-testnet:
              ansible_host: 217.160.186.47
              validator_name: "blab labla"
              validator_homepage: 'www.jedai.com'
              keybase_username: 'jd'
            jal-testnet:
              ansible_host: 78.46.82.11
            lk_testnet:
              ansible_host: 82.223.17.38
              lvm_enabled: True
            as_testnet:
              ansible_host: 217.79.189.50