---

- name: wait for restart windows
  hosts: remote
  become: yes
  tags:
    - validator.manage.restart.wait
  roles:
    - solana_validator_restart

- name: update solana validator
  hosts: remote
  become: yes
  roles:
    - solana_cli
    - solana_validator_restart
