---

# fix:
#   solana_user: "{{ solana_user | default('solana') }}"

#all:
cluster_environment: "{{ cluster_environment | default ('testnet') }}"
cluster_rpc_address: "{{ cluster_rpc_address | default('https://api.testnet.solana.com') }}"
ledger_path: "{{ ledger_path | default('/mnt/ledger') }}"
lvm_enabled: "{{ lvm_enabled | default(False) }}"  
lvm_vg: "{{ lvm_vg | default('vg00') }}" 

local_secrets_path: "{{ local_secrets_path | default('../.secrets') }}"
solana_user: 'solana' 
secrets_path: "{{ secrets_path | default('/home/' ~ fix.solana_user ~ '/.secrets', true) }}"
set_validator_info: "{{ set_validator_info | default(True) }}"
#service_user: "{{ service_user | default('solana') }}"
solana_validator_service: "{{ solana_validator_service | default('restarted')}}"

## ??
flat_path: "{{ flat_path | default(True) }}" ##??
##from input
keybase_username: "{{ keybase_username | default('') }}"  
ramdisk_size_gb: "{{ ramdisk_size_gb | default(64) }}"  
swap_file_size_gb: "{{ swap_file_size_gb | default(64) }}"  
upload_validator_keys: "{{ upload_validator_keys | default(True) }}"  
validator_homepage: "{{ validator_homepage | default('') }}"  
  
  
  
  
  

  

vhosts: "{{ host_hosts | default('remote') }}"
  
  
local:
  secrets_path: "{{ host.local_secrets_path }}"
  flat_path: "{{ host.flat_path }}"

cluster:
  environment: "{{ host.cluster_environment }}"
  entrypoint: "{{ host.cluster_environment }}.solana.com"
  rpc_address: "{{ host.cluster_rpc_address }}"

node:
#  lvm_enabled: "{{ host.lvm_enabled }}"
#  lvm_vg: "{{ host.lvm_vg }}"
  name: "{{host.validator_name}}"
  ramdisk_path: /mnt/ramdisk
  ramdisk_size_gb: "{{ host.ramdisk_size_gb }}"
  solana_user: "{{ host.solana_user }}"
  solana_home: "/home/{{ host.solana_user }}"
  swap_file_size_gb: "{{ host.swap_file_size_gb }}"

validator:
  accounts_path: "{{ node.ramdisk_path }}/solana"
  fail_if_no_validator_keypair: True
  homepage: "{{ host.validator_homepage }}"
  keybase_username: "{{ host.keybase_username }}"
  ledger_path: "{{ host.ledger_path }}"
  log_file: /var/log/solana-validator.log
#  name: "{{ host.validator_name }}"
  open_solana_ports_start: 8000
  open_solana_ports_end: 10000
  secrets_path: "{{ host.secrets_path }}"
  set_validator_info: "{{ host.set_validator_info }}"
  service_user: "{{ host.service_user }}"
  solana_validator_service: "{{ host.solana_validator_service }}"
  solana_rpc_port: 8899
  upload_validator_keys: "{{ host.upload_validator_keys }}"
  version: v1.6.9
  
monitoring:
  telegraf_database: v_metrics
  telegraf_urls: http://influx.thevalidators.io:8086
  telegraf_username: v_user
  telegraf_password: thepassword




