---
- name: Install python packages
  pip:
    name:
      - requests
      - numpy
    state: present
    executable: pip3
  tags:
    monitoring.script

- name: Create monitoring folder
  file:
    path: "{{ node.solana_home }}/monitoring"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0755
    state: directory
  tags: 
    - monitoring.script
    - monitoring.script.library

- name: Cleanup monitoring folder
  shell: "rm -rf {{ node.solana_home }}/monitoring/*"
  become: yes
  become_user: "{{ node.solana_user }}"
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload cluster monitoring library
  copy:
    src: files/cluster_monitoring_library.py
    dest: "{{ node.solana_home }}/monitoring/cluster_monitoring_library.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload common
  copy:
    src: files/common.py
    dest: "{{ node.solana_home }}/monitoring/common.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload request_utils
  copy:
    src: files/request_utils.py
    dest: "{{ node.solana_home }}/monitoring/request_utils.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload solana_rpc
  copy:
    src: files/solana_rpc.py
    dest: "{{ node.solana_home }}/monitoring/solana_rpc.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload measurement validator_info
  copy:
    src: files/measurement_validator_info.py
    dest: "{{ node.solana_home }}/monitoring/measurement_validator_info.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library


- name: Upload ouput validator info measurement
  copy:
    src: files/output_validator_info.py
    dest: "{{ node.solana_home }}/monitoring/output_validator_info.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload ouput validator info measurement
  copy:
    src: files/output_validators.py
    dest: "{{ node.solana_home }}/monitoring/output_validators.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload ouput validator info measurement
  copy:
    src: files/output_gossip.py
    dest: "{{ node.solana_home }}/monitoring/output_gossip.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags:
    - monitoring.script
    - monitoring.script.library


- name: Upload output script starter
  template:
    src: output_starter.sh.j2
    dest: "{{ node.solana_home }}/monitoring/output_starter.sh"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0755
  tags:
    - monitoring.script
    - monitoring.script.library

- name: Upload config script
  template:
    src: monitoring_config.py.j2
    dest: "{{ node.solana_home }}/monitoring/monitoring_config.py"
    owner: "{{ node.solana_user }}"
    group: "{{ node.solana_user }}"
    mode: 0644
  tags: 
    - monitoring.script
    - monitoring.script.library
