---
- name: Install python packages
  pip:
    name:
      - requests
      - numpy
    state: present
    executable: pip3
  tags:
    monitoring.script

- name: Delete script folder
  file:
    path: "{{ solana_home }}/monitoring"
    state: absent
  tags:
    monitoring.script     

- name: Create script folder
  file:
    path: "{{ solana_home }}/monitoring"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: 0755
    state: directory
  tags:
    monitoring.script

- name: Upload monitoring library
  copy:
    src: "files/{{ item }}"
    dest: "{{ solana_home }}/monitoring/{{ item }}"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: 0644
  with_items:
    - "cluster_monitoring_library.py"
    - "common.py"
    - "measurement_validator_info.py"
    - "output_gossip.py"
    - "output_validator_measurements.py"
    - "output_validators_info.py"
    - "output_validators.py"
    - "request_utils.py"
    - "solana_rpc.py"
    - "tds_info.py"
    - "validator_monitoring.py"
  tags:
    - monitoring.script
    - monitoring.script.library


- name: Upload monitoring script starter
  template:
    src: output_starter.sh.j2
    dest: "{{ solana_home }}/monitoring/output_starter.sh"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: 0755
  tags:
    - monitoring.script


- name: Upload config script
  template:
    src: monitoring_config.py.j2
    dest: "{{ solana_home }}/monitoring/monitoring_config.py"
    owner: "{{ solana_user }}"
    group: "{{ solana_user }}"
    mode: 0644
  tags:
    - monitoring.script

