---
- name: create download dir
  file:
    path: /tmp/solana
    state: directory
    owner: solana
    group: solana
  tags:
    - cli.install

- name: install solana
  block:
    - name: download latest solana release installer
      get_url:
        url: https://release.solana.com/{{ validator.version | default('stable') }}/install
        dest: /tmp/solana/
        mode: 0755

    - name: run solana installer
      shell: /tmp/solana/install
  become: yes
  become_user: solana
  tags:
    - cli.install

- name: remove installer
  file:
    path: /tmp/solana
    state: absent
  tags:
    - cli.install



