- name: update solana
  shell: "solana-install init {{ solana_version | default('stable') }}""
  become: yes
  become_user: "{{ solana_user }}"
  environment:
    PATH: "{{ solana_home }}/.local/share/solana/install/active_release/bin"
  tags:
    - cli.update
