---
all:
  children:
    local:
      children:
        lvm:
          hosts:
            server1:
              become: false
              ansible_connection: local
              ansible_python_interpreter: "{{ ansible_playbook_python }}"
              keybase_username: "server1"
            server2:
              become: false
              ansible_connection: local
              ansible_python_interpreter: "{{ ansible_playbook_python }}"
              keybase_username: "server2"
        non_lvm:
          hosts:
    remote:
      children:
        lvm:
          hosts:
            validator:
        non_lvm:
          hosts:
            validator2:

