---
- name: install solana validator
  hosts: all
  become: yes
  roles:
    - solana_validator_bootstrap
  
  # vars_prompt:
  #   - name: validator_key_path
  #     prompt: Where are your keys?
  #     private: no
  #   - name: validator_name
  #     prompt: What is your validator name?
  #     private: no
  #   - name: lvm_enabled
  #     prompt: LVM enabled (Yes/No)?
  #     default: No
  #     private: no

  tasks:
    # - name: debug variables
    #   debug:
    #     var: "{{ item }}"
    #   with_items:
    #    - secrets_path
    #    - ansible_user
#       - accounts_path
 #      - cluster_environment
      #  - name
      #  - entrypoint
      #  - ledger_path
    - name: show name
      debug:
        msg: "{{ solana_validator_service }}"
    - name: show cpu
      debug:
        msg: "{{ group_names }}"