---

# - name: wait for restart windows
#   hosts: all
#   become: yes
#   tags:
#     - validator.manage.restart.wait
#   roles:
#     - solana_validator_restart

- name: update solana validator
  hosts: all
  become: yes
  roles:
    - solana_cli
    - solana_validator_restart
