---

- name: wait for restart windows
  hosts: "{{ host_hosts }}"
  become: yes
  tags:
    - validator.manage.restart.wait
  roles:
    - solana_validator_restart

- name: update solana validator
  hosts: "{{ host.hosts }}"
  become: yes
  roles:
    - solana_cli
    - solana_validator_restart
